
service: usersbackend

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8

functions:
  userhandler:
    handler: src/handler.execuete

resources:
  Resources:
    ${file(userresources.yml)}
    ${file(partnerresources.yml)}
plugins:
  - serverless-python-requirements
