service: usersbackend

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.8

functions:
  userhandler:
    handler: src/userhandler.execuete
  partnerhandler:
    handler: src/partnerhandler.execuete

resources:
  Resources:
    UserResources:
      Type: AWS::CloudFormation::Stack
      Properties:
        TemplateFile: ${file(userresources.yml)}

    PartnerResources:
      Type: AWS::CloudFormation::Stack
      Properties:
        TemplateFile: ${file(partnerresources.yml)}

plugins:
  - serverless-python-requirements
